---
abstract: 'serialize / deserialize AMF data'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-AMF
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  Moose: 0
  Scalar::Util: 0
  perl: 0.008001
version: 0.01
