---
abstract: 'serialize / deserialize AMF data'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-AMF
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Moose: 0
  Scalar::Util: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02002
